---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkajsproducer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkajsproducer
  template:
    metadata:
      labels:
        app: kafkajsproducer
    spec:
      containers:
        - name: kafkajs-producer1
          image: nbchn/node-kafkaproducer
          imagePullPolicy: Always
